"""Quiz content for the Inter Branch English Grammar Quiz.

Each question has:
- instruction: the line above the question (e.g. "Fill in the blank with the correct verb form:")
  rendered at 40pt bold
- question: the main question text, rendered at 48pt bold
- hint: e.g. "(train)" shown in italics below the question
- options: list of option strings, each rendered at 48pt bold
- options_inline: if True, options are shown on one line like "Options: (is / are / was)"
"""

TEAM_NAMES = ["Team A", "Team B", "Team C", "Team D", "Team E", "Team F"]

ROUNDS = [
    {
        "number": 1,
        "title": "Present Tenses",
        "classes": {
            "XI": [
                {  # Team A
                    "instruction": "",
                    "question": "Each of the players ______ rigorously ever since the new coach took charge.",
                    "hint": "(train)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "",
                    "question": "Why ______ online classes over offline ones these days?",
                    "hint": "(prefer)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "",
                    "question": "My uncle has worked in this organization for years, yet he ______ any promotion so far.",
                    "hint": "(not / receive)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "",
                    "question": "She often reads novels, but today she ______ television.",
                    "hint": "(watch)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team E
                    "instruction": "",
                    "question": "They ______ with the suppliers for several weeks now.",
                    "hint": "(negotiate)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "",
                    "question": "I do not understand why he ______ so strangely these days.",
                    "hint": "(behave)",
                    "options": [],
                    "options_inline": False,
                },
            ],
            "XII": [
                {  # Team A
                    "instruction": "",
                    "question": "The teacher expects that students ______ their work punctually.",
                    "hint": "(submit)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "",
                    "question": "By next week, the researchers ______ their findings.",
                    "hint": "(publish)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "",
                    "question": "He ______ far more confident now.",
                    "hint": "(appear)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "",
                    "question": "This machine ______ efficiently if it is maintained regularly.",
                    "hint": "(operate)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team E
                    "instruction": "",
                    "question": "She has already completed the assignment, yet she ______ it again.",
                    "hint": "(revise)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "",
                    "question": "She ______ for the competition for the last three months.",
                    "hint": "(prepare)",
                    "options": [],
                    "options_inline": False,
                },
            ],
        },
    },
    {
        "number": 2,
        "title": "Past Tenses",
        "classes": {
            "XI": [
                {  # Team A
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "She ______ for the test before the teacher entered the class.",
                    "hint": "(prepare)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "Choose the correct option:\nWhich sentence is in the Past Continuous Tense?",
                    "question": "",
                    "hint": "",
                    "options": [
                        "(a) They play football.",
                        "(b) They were playing football.",
                        "(c) They have played football.",
                        "(d) They will play football.",
                    ],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "We ______ dinner when the guests arrived.",
                    "hint": "(have)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "Identify the tense used in the sentence:",
                    "question": "\u201CThe boys had completed their work before sunset.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team E
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "By the time the announcement was made, the audience ______ the hall.",
                    "hint": "(leave)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "Choose the correct verb to complete the sentence:",
                    "question": "If they ______ harder, they would have succeeded.",
                    "hint": "",
                    "options": ["try", "tried", "had tried"],
                    "options_inline": True,
                },
            ],
            "XII": [
                {  # Team A
                    "instruction": "Identify the tense used in the sentence:",
                    "question": "\u201CThe manager had approved the proposal before the meeting ended.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "They ______ this shop for more than a decade before they shifted to another city.",
                    "hint": "(run)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "She ______ for two hours before the train finally arrived.",
                    "hint": "(wait)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "Choose the correct form of the verb:",
                    "question": "She ______ the movie last night.",
                    "hint": "",
                    "options": ["see", "saw", "seen"],
                    "options_inline": True,
                },
                {  # Team E
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "The students ______ loudly when the principal entered the classroom.",
                    "hint": "(talk)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "Choose the correct option:\nWhich sentence is in the Past Perfect Continuous Tense?",
                    "question": "",
                    "hint": "",
                    "options": [
                        "(a) He was studying all night.",
                        "(b) He had been studying all night.",
                        "(c) He has studied all night.",
                        "(d) He studies all night.",
                    ],
                    "options_inline": False,
                },
            ],
        },
    },
    {
        "number": 3,
        "title": "Future Tenses",
        "classes": {
            "XI": [
                {  # Team A
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "By next year, she ______ her degree course.",
                    "hint": "(complete)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "Choose the correct option:\nWhich sentence is in the Future Continuous Tense?",
                    "question": "",
                    "hint": "",
                    "options": [
                        "(a) He writes a letter.",
                        "(b) He will be writing a letter.",
                        "(c) He wrote a letter.",
                        "(d) He has written a letter.",
                    ],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "Identify the tense used in the sentence:",
                    "question": "\u201CThis time tomorrow, they will be travelling across the mountains.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "At 8 p.m. tonight, we ______ dinner.",
                    "hint": "(have)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team E
                    "instruction": "Rewrite the sentence using the Future Perfect Continuous Tense:",
                    "question": "\u201CBy next month, he will work here for five years.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "She ______ soon after the meeting ends.",
                    "hint": "(arrive)",
                    "options": [],
                    "options_inline": False,
                },
            ],
            "XII": [
                {  # Team A
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "By the end of this week, the workers ______ the project.",
                    "hint": "(finish)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team B
                    "instruction": "Choose the correct option:\nWhich sentence is in the Future Perfect Tense?",
                    "question": "",
                    "hint": "",
                    "options": [
                        "(a) They will play cricket.",
                        "(b) They will be playing cricket.",
                        "(c) They will have played cricket.",
                        "(d) They played cricket.",
                    ],
                    "options_inline": False,
                },
                {  # Team C
                    "instruction": "Identify the tense used in the sentence:",
                    "question": "\u201CWhen you reach the station, the train will have already departed.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team D
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "This time next week, she ______ for her examinations.",
                    "hint": "(prepare)",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team E
                    "instruction": "Rewrite the sentence using the Future Perfect Tense:",
                    "question": "\u201CThey will finish the investigation before the deadline.\u201D",
                    "hint": "",
                    "options": [],
                    "options_inline": False,
                },
                {  # Team F
                    "instruction": "Fill in the blank with the correct verb form:",
                    "question": "By next month, he ______ in this company for ten years.",
                    "hint": "(work)",
                    "options": [],
                    "options_inline": False,
                },
            ],
        },
    },
    {
        "number": 4,
        "title": "Determiners",
        "classes": {
            "XI": [
                {  # Team A
                    "instruction": "",
                    "question": "______ student participated in the competition.",
                    "hint": "",
                    "options": ["Every", "Much", "Few"],
                    "options_inline": True,
                },
                {  # Team B
                    "instruction": "",
                    "question": "______ books belong to the library.",
                    "hint": "",
                    "options": ["Those", "Little", "Any"],
                    "options_inline": True,
                },
                {  # Team C
                    "instruction": "",
                    "question": "______ effort was made to resolve the conflict.",
                    "hint": "",
                    "options": ["Little", "Many", "Several"],
                    "options_inline": True,
                },
                {  # Team D
                    "instruction": "",
                    "question": "______ subject do you like the most?",
                    "hint": "",
                    "options": ["Which", "Few", "Much"],
                    "options_inline": True,
                },
                {  # Team E
                    "instruction": "",
                    "question": "______ applicants were shortlisted.",
                    "hint": "",
                    "options": ["Several", "Much", "Little"],
                    "options_inline": True,
                },
                {  # Team F
                    "instruction": "",
                    "question": "______ decision surprised everyone.",
                    "hint": "",
                    "options": ["Her", "Many", "Few"],
                    "options_inline": True,
                },
            ],
            "XII": [
                {  # Team A
                    "instruction": "",
                    "question": "There isn\u2019t ______ justification for such behaviour.",
                    "hint": "",
                    "options": ["much", "many", "several"],
                    "options_inline": True,
                },
                {  # Team B
                    "instruction": "",
                    "question": "He has ______ patience for careless mistakes.",
                    "hint": "",
                    "options": ["little", "few", "several"],
                    "options_inline": True,
                },
                {  # Team C
                    "instruction": "",
                    "question": "______ of the proposals were rejected unanimously.",
                    "hint": "",
                    "options": ["Most", "Much", "Each"],
                    "options_inline": True,
                },
                {  # Team D
                    "instruction": "",
                    "question": "She bought ______ pair of shoes.",
                    "hint": "",
                    "options": ["a", "an", "the"],
                    "options_inline": True,
                },
                {  # Team E
                    "instruction": "",
                    "question": "I don\u2019t have ______ clarity regarding the policy.",
                    "hint": "",
                    "options": ["any", "many", "few"],
                    "options_inline": True,
                },
                {  # Team F
                    "instruction": "",
                    "question": "______ of the answers was correct.",
                    "hint": "",
                    "options": ["Each", "Many", "Few"],
                    "options_inline": True,
                },
            ],
        },
    },
    {
        "number": 5,
        "title": "Subject\u2013Verb Agreement",
        "classes": {
            "XI": [
                {  # Team A
                    "instruction": "",
                    "question": "Either the principal or the senior teachers ___ responsible for implementing the decision.",
                    "hint": "",
                    "options": ["is", "are", "was"],
                    "options_inline": True,
                },
                {  # Team B
                    "instruction": "Choose the correct verb:",
                    "question": "A group of tourists ___ visiting the museum.",
                    "hint": "",
                    "options": ["is", "are", "were"],
                    "options_inline": True,
                },
                {  # Team C
                    "instruction": "",
                    "question": "Every student, along with the mentors, ___ expected to attend the orientation.",
                    "hint": "",
                    "options": ["is", "are", "were"],
                    "options_inline": True,
                },
                {  # Team D
                    "instruction": "Choose the correct verb:",
                    "question": "Neither the manager nor the employees ___ satisfied with the decision.",
                    "hint": "",
                    "options": ["is", "are", "was"],
                    "options_inline": True,
                },
                {  # Team E
                    "instruction": "",
                    "question": "The furniture, including the chairs and tables, ___ damaged during transit.",
                    "hint": "",
                    "options": ["was", "were", "are"],
                    "options_inline": True,
                },
                {  # Team F
                    "instruction": "Fill in the blank:",
                    "question": "One of the boys ___ selected for the team.",
                    "hint": "",
                    "options": ["has", "have", "had"],
                    "options_inline": True,
                },
            ],
            "XII": [
                {  # Team A
                    "instruction": "",
                    "question": "Politics, along with economics, ___ his favourite subject.",
                    "hint": "",
                    "options": ["is", "are", "were"],
                    "options_inline": True,
                },
                {  # Team B
                    "instruction": "Choose the correct verb:",
                    "question": "Both the author and the editor ___ present at the launch.",
                    "hint": "",
                    "options": ["is", "are", "was"],
                    "options_inline": True,
                },
                {  # Team C
                    "instruction": "",
                    "question": "The jury, as well as the witnesses, ___ examined thoroughly.",
                    "hint": "",
                    "options": ["has", "have", "had"],
                    "options_inline": True,
                },
                {  # Team D
                    "instruction": "Choose the correct verb:",
                    "question": "Bread and butter ___ my usual breakfast.",
                    "hint": "",
                    "options": ["is", "are", "were"],
                    "options_inline": True,
                },
                {  # Team E
                    "instruction": "",
                    "question": "A chain of bookstores ___ recently expanded across the country.",
                    "hint": "",
                    "options": ["has", "have", "had"],
                    "options_inline": True,
                },
                {  # Team F
                    "instruction": "Fill in the blank:",
                    "question": "Neither the teacher nor the students ___ ready for the test.",
                    "hint": "",
                    "options": ["is", "are", "was"],
                    "options_inline": True,
                },
            ],
        },
    },
]
